SymphonyPlatformSolutions/symphony-ui-toolkit

.circleci/config.yml
spec/components/tooltip/Tooltip.spec.tsx

https://perzoinc.atlassian.net/browse/APP-3820
**Change**
- Disable random test
- Increase NODE memory to 4096 because the tests were failing due to a 'ENOMEM: not enough memory, read' error.
(Solution of the problem : https://discuss.circleci.com/t/unit-tests-enomem-not-enough-memory-read/35695/2)
Per default:
- RAM size on CircleCI is 4096 : https://circleci.com/docs/2.0/configuration-reference/#resource_class
- NODE is limited to 2GB on some 64bit systems. The CircleCI support explain how to increase to 4096 (See support page: https://support.circleci.com/hc/en-us/articles/360009208393-How-can-I-increase-the-max-memory-for-Node-)

APP-3820 Increase memory to 4096

---

package.json
spec/components/date-picker/DatePicker.spec.tsx
yarn.lock

https://perzoinc.atlassian.net/browse/APP-3922
**Changes**
- Set minimum lodash version to 4.17.21 because it includes a security fix. (See: https://app.snyk.io/vuln/SNYK-JS-LODASH-1040724)
(FYI, fix by defining the version resolution. See https://classic.yarnpkg.com/en/docs/selective-version-resolutions)

APP-3922 Security Fix: Set minimum lodash version to 4.17.21

---

spec/components/crop-content/CropContent.spec.tsx
spec/components/dropdown/Dropdown.spec.tsx
spec/components/expandable-card/ExpandableCard.spec.tsx
src/components/crop-content/CropContent.tsx
src/components/expandable-card/ExpandableCard.tsx
stories/CropContent.stories.tsx
stories/ExpandableCard.stories.tsx

https://perzoinc.atlassian.net/browse/APP-3943
- CropContent: Add onToggle props that returns the element itself and the collapsed boolean
- ExpandableCard: Add onToggle props that returns the element itself and the collapsed boolean
https://github.com/SymphonyOSF/NEXUS/pull/1245

APP-3943 - Add props onToggle to Expandable Card and CropContent

---

.storybook/preview.js
package.json
spec/components/date-picker/DatePicker.spec.tsx
src/components/date-picker/DatePicker.tsx
src/components/input/TextComponent.tsx
stories/TextField.stories.tsx
stories/stories.scss
yarn.lock

https://perzoinc.atlassian.net/browse/APP-4027
- Add new prop `decoratorElement`, the idea is to have the "masked" feature more generic and give the possibility to have something else
- New `isMasked` in order to force the TextField to show "••••••••"
- The `masked` attribute has been deprecated since it's a combination of `decoratorElement` and `isMasked`
Styles https://github.com/SymphonyPlatformSolutions/symphony-bdk-ui-toolkit-styles/pull/80

APP-4027 - Add right decorator props and deprecate masked prop

---

package.json
yarn.lock

Bump uitoolkit-styles to 1.5.0-rc.1
Changelog: https://github.com/SymphonyPlatformSolutions/symphony-bdk-ui-toolkit-styles/releases/tag/v1.5.0-rc.1

APP-4051 chore(uitoolkit-styles): Bump to 1.5.0-rc.1

---

spec/components/input/TextComponent.spec.tsx
src/components/input/TextComponent.tsx

https://perzoinc.atlassian.net/browse/APP-4133
**Changes**
Support a single decorator and an array of decorator in the TextComponent.
Now it possible to use:
- either a single decorator (without key)
```
<TextComponent
type={Types.TEXTFIELD}
rightDecorators={<button>{decoratorName}</button>}
/>
```
- either an array of decorators (with keys)
```
<TextComponent
type={Types.TEXTFIELD}
rightDecorators={[
<button id={decoratorId1} key="decorator-1">
{decoratorName1}
</button>,
<button id={decoratorId2} key="decorator-2">
{decoratorName2}
</button>,
]}
/>
```
(Also fix a warning in the TextComponent unit test by adding onChange method)

APP-4133 Support a single decorator and an array of decorator

---

src/components/dropdown/CustomRender.tsx
src/components/dropdown/Dropdown.tsx
stories/Dropdown.stories.tsx

https://perzoinc.atlassian.net/browse/APP-3931
Create a `mode` prop that can be either nested (or aligned)
- The nested is only applied on the default render
- We don't do anything special in "aligned" mode
Bonus: Reorder the props
What do you think about the implementation
https://github.com/SymphonyPlatformSolutions/symphony-bdk-ui-toolkit-styles/pull/90

APP-3937 feat(dropdown): create nested mode

---

.circleci/config.yml
package.json

https://perzoinc.atlassian.net/browse/APP-4064
Include code climate to add the step to check the diff coverage

APP-4064 ci(diff-coverage): add code climate to the ci config

---

src/components/dropdown/Dropdown.tsx

ClassName prop was mentioned as a prop to the DropDown component, but that was never used. So this PR focuses on adding it to the parent div.

DropDown component : assign the className props to the outer div

---

src/components/dropdown/Dropdown.tsx

With this change, the async dropdown has the possibility to differentiate the options loaded when the dropdown is rendered and when the user starts typing.

APP-3518 Async dropdown with different defaultOptions

---

package.json
yarn.lock

**Jira**
https://perzoinc.atlassian.net/browse/APP-4177
**Changes**
Version 4.3.1 was already used in the yarn.lock, but to be sure we also define v4.3.1 as the minimum version of react-select in the package.json.
(To always have the fix of React-Select: https://github.com/JedWatson/react-select/releases/tag/react-select%404.3.1)

APP-4177 Set v4.3.1 as the minimum version of react-select

---

spec/components/crop-content/CropContent.spec.tsx
src/components/crop-content/CropContent.tsx

This allows us to recalculate the full height of the container when content changes.

APP-4230 - fix size not updating on dom change

---

src/components/tooltip/Tooltip.tsx
src/components/tooltip/helpers.tsx

:warning: Reverts SymphonyPlatformSolutions/symphony-bdk-ui-toolkit-components#235 because it introduced a regression.
When we click on 'Got IT' then the tooltip closes only if the mouse leaves the tooltip.
Demo:

Revert "fix: tooltip behaviour"

---

src/components/tooltip/Tooltip.tsx
stories/Tooltip.stories.tsx

https://perzoinc.atlassian.net/browse/APP-4242
From bug explained here: 
https://user-images.githubusercontent.com/56824367/122567353-dd107c80-d048-11eb-9a26-cc689d7489f7.mov
https://perzoinc.atlassian.net/wiki/spaces/EIS/pages/1953630703/Weekly+status+meeting+minutes#issue-tooltip-%2F-Switch-disabled
The resolution is to wrap the children inside a span, a solution is to add it directly to the general component, so the workaround doesn't need to be added by the consumer

APP-4242 - Tooltip : Wrap the children in a span

---

spec/components/modal/Modal.spec.tsx
src/components/modal/Modal.tsx
stories/Modal.stories.tsx

https://perzoinc.atlassian.net/browse/APP-4195
**Changes**
- Remove enzyme from Modal tests to use only testing-library
- Add tests for: ModalTitle, ModalHeader, ModalBody, ModalFooter
- Allow sending additional parameters (class, aria, etc...) to the ModalTitle, ModalHeader, ModalBody, ModalFooter
- Fix: 'undefined' class when no size was given in the attribute
**Test coverage of the Modal**
(Related PR: https://github.com/SymphonyPlatformSolutions/symphony-bdk-ui-toolkit-styles/pull/106)

APP-4195 Send additional attributes to the ModalTitle/ModalHeader/ModalBody/ModalFooter

---

spec/components/banner/Banner.spec.tsx
src/components/banner/Banner.tsx
src/components/banner/index.ts
src/components/banner/interfaces.ts
src/components/index.ts
stories/Banner.stories.tsx

**EIS-3348: Add Banner component**
- add Banner.ts and BannerUtils.ts
- add related unit tests
- add related stories
- export Banner component
Ticket: [https://perzoinc.atlassian.net/browse/EIS-3348](https://perzoinc.atlassian.net/browse/EIS-3348)
Figma: [https://www.figma.com/file/V0VKw74594EyCKHwqYk6LV/%E2%9D%96-SDS-Core-Component-Library?node-id=5272%3A9287](https://www.figma.com/file/V0VKw74594EyCKHwqYk6LV/%E2%9D%96-SDS-Core-Component-Library?node-id=5272%3A9287)
Related PR (styles): [https://github.com/SymphonyPlatformSolutions/symphony-bdk-ui-toolkit-styles/pull/107](https://github.com/SymphonyPlatformSolutions/symphony-bdk-ui-toolkit-styles/pull/107)
--------
**EDIT**
- `onClickAction` has been renamed to `onAction`
- `onClickClose` has been renamed to `onClose`
- `canClose` has …

EIS-3348: Add Banner component

---

jest.config.js
package.json
spec/components/input/InputDecorator.spec.tsx
spec/utils/utils.spec.js
src/components/input/InputDecorator.tsx
src/utils/index.ts
stories/Validation.stories.tsx
yarn.lock

https://perzoinc.atlassian.net/browse/APP-4318
**Fix**
Fix 'onChange' and 'onBlur' methods are not called in InputDecorator
**Description of the problem:** The 'onChange' and 'onBlur' were injected by the Validation component and were overwriting those defined on the input.
**Solution:** The inputDecorator calls the onChange and onBlur methods on the Validation, then calls the methods defined on the input.
**Other changes**
- Add jest-extended in devDependencies to be able to use 'toHaveBeenCalledBefore'

APP-4318 Fix 'onChange' and 'onBlur' methods are not called in InputDecorator

---

src/components/input/InputDecorator.tsx

to handle layout we need the prop classname to be added to the InputDecorator Component

EIS-3533 - add classname prop to InputDecorator

---

package.json
spec/components/dropdown/Dropdown.spec.tsx
src/components/dropdown/CustomRender.tsx
src/components/dropdown/Dropdown.tsx
stories/Dropdown.stories.tsx
stories/stories.scss
yarn.lock

https://perzoinc.atlassian.net/browse/RTC-10806
- Added menuShouldScrollIntoView argument from react-select.
See SDS (Symphony Design System) for latest designs on the Select component - https://www.figma.com/file/V0VKw74594EyCKHwqYk6LV/%E2%9D%96-SDS-Core-Component-Library?node-id=5453%3A17120
https://github.com/SymphonyPlatformSolutions/symphony-bdk-ui-toolkit-styles/pull/115 - has to merge first.
Tested with MacOS VoiceOver and aria-label works on the component.

RTC-10806 - Improvements to the Dropdown component

---

spec/components/dropdown/Dropdown.spec.tsx
src/components/input/InputDecorator.tsx
src/components/input/TextComponent.tsx
src/components/selection/SelectionInput.tsx
stories/Validation.stories.tsx

https://perzoinc.atlassian.net/browse/APP-4317
**Change:**
Fix not supported property on Checkbox and fix lint warnings
Description: Some props are automatically injected by the Validation Component and are not used in Native HTML tags (like the input). So, I mark them as unused variables in the Component and don't inject them in the native input.
Before the fix:
With the fix:

APP-4317 Fix not supported property on Checkbox and fix lint warnings

---

spec/components/badge/Badge.spec.tsx
src/components/badge/Badge.tsx
src/components/badge/index.ts
src/components/badge/interfaces.ts
src/components/index.ts
stories/Badge.stories.tsx

- added "default" as a value for the variant prop
- created a BadgeType type
- reorganised files to be consistent with Banner implementation
IMO it is better to have a BadgeType enum instead of hardcoded strings.
It shouldn't be a breaking change as the values of the enum are kept.
the style is now correctly defined:
and we can change on the fly:

EIS-3537 - Badge default variant

---

spec/components/dropdown/Dropdown.spec.tsx
src/components/dropdown/Dropdown.tsx

When several options had the same value and the user selects one of them, they were all marked as selected. 
When several options had the same value and the user selects one of them, there is only one displayed as selected. 
[Jira ticket](https://perzoinc.atlassian.net/browse/APP-4191)

APP-4191 Select only one option if they have the same value

---

spec/components/text-ellipsis/TextEllipsis.spec.tsx
src/components/index.ts
src/components/text-ellipsis/TextEllipsis.tsx
src/components/text-ellipsis/index.ts
src/components/tooltip/Tooltip.tsx
stories/TextEllipsis.stories.tsx
stories/Typography.stories.tsx

https://perzoinc.atlassian.net/browse/APP-3334
- Added TextEllipsis component
-- Will show Tooltip when text is ellipsed
-- You can set number of rows before ellipse
Two row ellipse
https://github.com/SymphonyPlatformSolutions/symphony-bdk-ui-toolkit-styles/pull/120 - Needs to merge first.
Should tooltip on ellipsed and on hover be optional? Can add another flag for it.

APP-3334 - Adding TextEllipsis

---

docs/advanced-usage.md
spec/core/hoc/StylesInjection.spec.tsx
src/components/index.ts
src/core/hoc/StylesInjection.tsx
src/core/hoc/index.ts

Created an <UIToolkit> component that takes care of injecting styles from different styling libraries to the correct context. UIToolkit has `styled-components` and  `@emotion` right now that need help injecting their styles to the correct document. Instead of users of this library needing these they need only one import, `<UIToolkit>` with the injectionPoint props that will take of the injection to the correct libraries.

Added a <StylesInjection> HOC that takes care of injecting styles from different styling libraries to the correct document

---

spec/components/tooltip/Tooltip.spec.tsx
src/components/tooltip/Tooltip.tsx

Problem is object in classnames: { className } => always have class className in your html, it is not name of class which you pass from props(className)
It should be [className] instead of {className}
(https://github.com/JedWatson/classnames)
[Issue](https://github.com/SymphonyPlatformSolutions/symphony-bdk-ui-toolkit-components/issues/280)

fix bug 280: classname of tootltip is wrong

---

spec/components/dropdown-menu/DropdownMenu.spec.tsx
src/components/dropdown-menu/DropdownMenu.tsx

Allow user to navigate between menu options using keyboard and activate a certain option by pressing enter. 
https://user-images.githubusercontent.com/32852556/133571267-c9adbb27-d434-48c3-9c7e-079b9e587177.mov

Allow keyboard navigation in dropdowm menu

---

package.json
src/components/input/InputDecorator.tsx
src/components/input/TextComponent.tsx
src/components/selection/SelectionInput.tsx
src/core/hoc/StylesInjection.tsx
yarn.lock

https://perzoinc.atlassian.net/browse/APP-4518
**Changes**
Temporarily use shortId instead of nanoid because nanoid is not transpiled for IE11
See comment in issue: https://github.com/ai/nanoid/issues/210
And nanoid release note: https://github.com/ai/nanoid/releases/tag/3.0.0.

APP-4518 Temporarily use shortId instead of nanoid because nanoid is not transpiled for IE11

---

docs/advanced-usage.md
src/components/text-ellipsis/TextEllipsis.tsx
stories/TextEllipsis.stories.tsx

https://perzoinc.atlassian.net/browse/RTC-10961
- Applying the `__multiple-rows` property to text-ellipsis if rows are > 1
- Adding documentation regarding linking `react` and `react-dom`
- tooltipProps on TextEllipsis should be a Partial
https://github.com/SymphonyPlatformSolutions/symphony-bdk-ui-toolkit-styles/pull/139

RTC-10961 - Improving TextEllipsis component

---

spec/components/selection/SelectionInput.spec.tsx
src/components/selection/SelectionInput.tsx
stories/Checkbox.stories.tsx

**APP-4567 / APP-4568: `SelectionInput` update for the SDS alignment**
- adds the `tk-{type}--disabled` class to the parent div --> allows to change the label color from CSS when the input is disabled (because from the `label` location, we were not able to access the input's `disabled` attribute)
- updates `SelectionInput` tests
--------
Related style PR: https://github.com/SymphonyPlatformSolutions/symphony-bdk-ui-toolkit-styles/pull/152
Related tickets:
- https://perzoinc.atlassian.net/browse/APP-4567
- https://perzoinc.atlassian.net/browse/APP-4568
-------
https://user-images.githubusercontent.com/66251236/137888184-5f94ceb0-6eb1-426e-af6e-9751f916c2cc.mov

APP-4567 / APP-4568: `SelectionInput` update for the SDS alignment

---

src/components/button/Button.tsx
stories/Button.stories.tsx

https://perzoinc.atlassian.net/browse/APP-4649
**Changes**
Remove the breaking change on the Button component (impacting RTC team).
It removes the 'span' which was added in the Button Component to support the size of the button in "loading" state.
Another solution to support the size of the button is provided in this PR: Use transparent color and use an aria-label for the screenreaders.
**Demo**

APP-4649 Remove the breaking change on the Button component

---

spec/components/text-ellipsis/TextEllipsis.spec.tsx
src/components/text-ellipsis/TextEllipsis.tsx

If the child is undefined, the TextEllipsis returns an error because description cannot be empty for tooltip.

RTC-11877 - Not render a tooltip in TextEllipsis if tooltipProps.description or children are undefined

---

src/components/dropdown/CustomRender.tsx
src/components/dropdown/Dropdown.tsx
src/components/dropdown/interfaces.ts
src/components/input/TextComponent.tsx
stories/Dropdown.stories.tsx

https://perzoinc.atlassian.net/browse/APP-4520
- Add size prop
- Add destructive prop
- Adjust keyboard navigation to the hint
- I am having issue implementing size: small, the height should be 24px, but it is currently 32px (as medium) (--> not proposing small size for now) https://perzoinc.atlassian.net/browse/APP-4689
Styles: https://github.com/SymphonyPlatformSolutions/symphony-bdk-ui-toolkit-styles/pull/176

APP-4520 feat(dropdown): add size and variant prop

---

spec/components/dropdown-menu/DropdownMenu.spec.tsx
src/components/dropdown-menu/DropdownMenu.tsx

For the need of [this CES ticket](https://perzoinc.atlassian.net/browse/CES-5147), I need to replace our DropDownMenu with the one from the UI Toolkit.
When implementing it, I found an issue because event listener `click` triggered the `mouseEventHandler` event for each click every where on the page **even if the menu is not open**.
So, when you click on a button that should open the menu, the `close()` is automatically triggered in the same time: so we can't open the menu.
I've just added a watch on `show` property in order to skip event listeners.
In short:
- `show=false`: we don't need to listen events
- `show=true`: we need to listen events

fix: unwanted behaviour when the menu is not displayed

---

spec/components/time-picker/TimePicker.spec.tsx
src/components/date-picker/DatePicker.tsx
src/components/dropdown/CustomRender.tsx
src/components/dropdown/Dropdown.tsx
src/components/dropdown/interfaces.ts
src/components/time-picker/TimePicker.tsx
src/components/time-picker/interfaces.ts

https://perzoinc.atlassian.net/browse/APP-4603
**Changes**
-TimePicker: Pass the `onCopy`/`onCut`/`onDrag` props to the Dropdown component
-Dropdown: Apply `onCopy`/`onCut`/`onDrag` props on the Input if they are defined
(FYI, I had to use 'any' in the `isOptionDisabled` and `isOptionSelected` props because I got a TypeScript error. In a major UI-TK version, we will replace the `any` with the right type.)
**Demo**
In NEXUS, it fixes the prevent copy feature
https://user-images.githubusercontent.com/66668470/143472147-695f583a-0a2e-46b0-9834-35ea9abf2a6d.mov

APP-4603  Pass onCopy/onCut/onDrag on Dropdown component

---

stories/TextEllipsis.stories.tsx

Before:
After:
Sample before:
Sample after:

feat: improve Text Ellipsis stories

---

stories/Modal.stories.tsx

Improving Modal component docs (all stories).
I've just added `StoryBackground` component to reduce the `height` only for Storybook because the modal's backdrop was over the `Show Code` button from the Docs.
Now we can click on it and see how component works.
Sample before:
Sample after:

fix: Show Code button is now accessible

---

src/components/dropdown/interfaces.ts

https://perzoinc.atlassian.net/browse/APP-4734 - See ticket for more details
After this PR - https://github.com/SymphonyPlatformSolutions/symphony-bdk-ui-toolkit-components/pull/308 - we got two interfaces for `onChange` in `Dropdown`. One which was the original one and one from `React.HTMLProps<HTMLInputElement>`. I looked at the event and it's more in line with the other one + we would keep backwards compatibility.

APP-4734 - Omitting the onChange props from React.HTMLProps<HTMLInputElements>

---

package.json
publish.sh

**Changes**
Replace NPM commands by Yarn because it's a pre-requisite to merge UI-TK repositories.

Replace NPM commands by Yarn

---

src/components/date-picker/DatePicker.tsx
src/components/dropdown/interfaces.ts
src/components/time-picker/interfaces.ts

https://perzoinc.atlassian.net/browse/APP-4755
**Changes**
A regression was introduced with PR #330. The 'value' prop type was overlapped by the HTMLInput interface.
**Before fix**
**After fix:**

APP-4755 Fix overlapping interfaces for the value property

---

spec/components/selection/SelectionInput.spec.tsx
src/components/selection/SelectionInput.tsx

Prevent to have the following warning when passing a node to the label prop
```
"Warning: Failed prop type: Invalid prop `label` of type `object` supplied to `Checkbox`, expected `string`.
```

APP-4654 feat(SelectionInput): accept node as label

---

package.json
spec/components/input/InputDecorator.spec.tsx
src/components/input/InputDecorator.tsx
src/components/label-tooltip-decorator/LabelTooltipDecorator.tsx
yarn.lock

See description here for more context: https://github.com/SymphonyPlatformSolutions/symphony-bdk-ui-toolkit-components/pull/391
- Add a classname to the hint, so the style can decorate it and be independente of the icon
Bonus
- Remove mandatory `child` in the `InputDecorator`

feat(input): add a classname to the hint to be more flexible

---

packages/styles/src/components/atoms/_dropdown-menu.scss

https://perzoinc.atlassian.net/browse/APP-4857
Storybook and SFE-Lite have different box-sizing causing a discrepancy how `tk-dropdown-menu__item` gets rendered because it has a height property.
I think 1) Storybook should use border-box as well to reflect the SFE-Lite environment and 2) All components should have a box-sizing enforced so there are no implicit dependencies causing a different rendering. Future discussion and PRs.

APP-4857 - Enforcing box-sizing to tk-dropdown-menu__item

---

packages/components/stories/TimePicker.stories.tsx
packages/components/stories/Tooltip.stories.tsx

Fix code preview displays "No display name" by applying the fix described [here](https://github.com/storybookjs/storybook/issues/12596#issuecomment-947940406)
**Before**
**After**

Fix: Doc code preview "No display name"

---

packages/components/src/components/loader/Loader.tsx

Fix: 'undefined' variant is added in the Loader component when no variant is defined.
Before
After

Fix: Remove "undefined" variant in the Loader component

---

packages/components/spec/components/validation/Validation.spec.tsx
packages/components/src/components/validation/Validation.tsx
packages/components/stories/Validation.stories.tsx

In mobile the order of blur and change are not aligned with the desktop browser
This made validation to enter in an infinite loop for dropdown component as it triggers both events on item selection
[JIRA_Ticket](https://perzoinc.atlassian.net/browse/APP-4932 )

APP-4932 - Refactor Validation to avoid infinte loops in mobile

---

packages/styles/src/components/atoms/_dropdown-menu.scss

There needs to be padding on the right side or the text is super close to the edge.
See Figma SDS for reference - https://www.figma.com/file/V0VKw74594EyCKHwqYk6LV/%E2%9D%96-SDS-Core-Component-Library?node-id=3575%3A99
Before:
After:

Fixing padding for menuDropdownItem

---

packages/components/spec/components/dropdown/Dropdown.spec.tsx
packages/components/src/components/dropdown/CustomRender.tsx
packages/components/src/components/dropdown/Dropdown.tsx
packages/components/src/components/dropdown/interfaces.ts

**APP-4919: Fix displayed option label in Dropdown (multi select)**
https://perzoinc.atlassian.net/browse/APP-4919
When using `Dropdown` (with `isMultiSelect` being `true`), and providing options that does not include a `label` attribute, the option labels are not displayed.
- adds `bindLabel` prop in `Dropdown`, so we can define a way to get the label from an option (default being `(option) => option.label`)
- plugs this `bindLabel` prop to the `getOptionLabel` prop of the `DropdownTag`
- updates the `MultiValue` custom renderer so that it calls `getOptionLabel(option)` instead of `option.label`
- adds related tests
-----
**Before**
https://user-images.githubusercontent.com/66251236/153578986-201aa3a6-f028-443e-9d53-1f038ca8db67.mov
-----
**After** …

APP-4919: Fix displayed option label in Dropdown (multi select)

---

packages/styles/src/uitoolkit-components/_select.scss

https://perzoinc.atlassian.net/browse/C2-14729
Apply the color to `.tk-select__input` instead of `.tk-select__control--menu-is-open` `.tk-select__control--menu-is-focus`

style(dropdown): make the color input style more robust

---

packages/components/src/components/modal/Modal.tsx

The modal component has a hardcoded tabIndex "-1", there is no way to change it as it currently does not accept regular html props.  This prevents us from focusing the modal using sequential keyboard navigation. 
[JIRA_Ticket](https://perzoinc.atlassian.net/jira/software/c/projects/RTC/boards/91?modal=detail&selectedIssue=RTC-9700&quickFilter=5206t)

Allow modal to accept html props

---

packages/components/src/components/selection/Checkbox.tsx
packages/components/src/components/selection/Radio.tsx
packages/components/stories/Checkbox.stories.tsx
packages/components/stories/Radio.stories.tsx

Checkbox & Radio: add types in the documentation
SelectionInput already had the props type, but not the Checkbox and Radio
This is not a breaking change, as these component were already restrited to the types (implictly from SelectionInput). I am just making it explicit
Before
After

doc(checkbox): add types documentation

---

packages/components/spec/components/dropdown/Dropdown.spec.tsx
packages/components/src/components/dropdown/Dropdown.tsx

**APP-4818: Fix Dropdown's `...otherProps`**
This commit makes the `Dropdown` props override possible, by placing the `...otherProps` at the end of the `DropdownTag`.
- All the known props are now extracted from `this.props` (so we don't have any residual known props in `otherProp`)
- All the inner functions are now in the `render` method (to avoid tslint unused var warning)
- Adds related unit test
- Adds unit test for `onInit` prop
Related ticket: https://perzoinc.atlassian.net/browse/APP-4918
--------

APP-4818: Fix Dropdown's `...otherProps`

---

packages/components/spec/components/dropdown/Dropdown.spec.tsx
packages/components/src/components/dropdown/Dropdown.tsx
packages/components/src/components/dropdown/interfaces.ts
packages/components/stories/Dropdown.stories.tsx

**APP-4916: Add `CreatableSelect` and `CreatableAsyncSeelct` to the `Dropdown` component**
This commit adds a new `isCreatable` prop to the `Dropdown` component.
When this prop is `true`, the user can create new options at runtime, according to the inputValue. This is compatible with simple selects, multi select and async selects.
Optionally, 2 other props can be provided along with this `isCreatable` prop:
- `getNewOptionData`: function telling how to structure the created option based on the user input (default one will create options using this structure `{ value: $userInput, label: $userInput }`)
- `isValidNewOption`: function telling if the inputValue can be converted into a new option (default one always returns `true`)
Briefly:
- the `DropdownTag` is now chosen according to the …

APP-4916: Add CreatableSelect and CreatableAsyncSeelct to the Dropdown component

---

packages/components/src/components/dropdown/CustomRender.tsx

A Dropdown with `isMultiSelect` being `false`, always render a caret icon on the right.
When `isMultiSelect` is `true`, we need to set `displayArrowIndicator` to `true` as well if we want to have an icon on the right. Unfortunately, simple select uses a caret, and multi select uses an arrow.
This commit set the multi select icon to be a caret.
https://perzoinc.atlassian.net/browse/APP-5102
**Before**
**After**

APP-5102: Align simple and multi select right icon

---

packages/styles/.circleci/config.yml

Disable temporary Visual Tests in Dark mode
I created the ticket https://perzoinc.atlassian.net/browse/APP-5149 to not forget to fix it.

APP-5149 Disable temporary Visual Tests in Dark mode

---

packages/components/spec/components/modal/Modal.spec.tsx
packages/components/src/components/modal/Modal.tsx

When the LeftNav is collapsed, dragging the Symphony-C9 extension Instant Voice "Add user" modal, is also dragging the Instant Voice active call widget simultaneously, this PR fix the issue.
https://perzoinc.atlassian.net/browse/RTC-13610

RTC-13610 Fix Modal drag propagation

---

packages/components/src/components/icon/Icon.tsx
packages/styles/src/icons/_index.scss
packages/styles/src/icons/templates/tk-icons.scss.hbs
packages/styles/src/icons/templates/tk-icons.stories.js.hbs

Default CSS selectors with ^= and *= were creating perf bottleneck in C2 mostly because they force the browser to check for every single dom element to match classes against the 2 generic selectors. In a grid with 20 chats this starts to get significant. By adding a dedicated `.tk-icon` class the browser is able to better optimise its recalculate style. 
[C2-18455](https://perzoinc.atlassian.net/browse/C2-18455)
[C2-18455]: https://perzoinc.atlassian.net/browse/C2-18455?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

C2-18455 - Add specific CSS class for tk icons

---

packages/components/package.json

When linking locally with yalc the entrypoint was `dist/src/index.js` but shouldn't have changed it because published `index.js` is correct.
Update: I think `src/index.js` is the most correct.

Fix main entrypoint

---

packages/components/stories/DropdownMenu.stories.tsx
packages/styles/src/components/atoms/_dropdown-menu.scss
packages/styles/src/utils/mixins/_list.scss
packages/styles/stories/dropdownMenu.stories.js

It was impossible to implement properly sub menus containing icons, when hovering, the icon style is forced to a light color, that would also apply to all the icons of the sub-menu.
Icons in sub-menu are light because of hover on the parent menu item
---
I also fixed some markup formatting here and there
cc @antoinerollindev @axeleriksson147 @symphony-jean-michael

fix(dropdown-menu): reducing icon selector weight

---

packages/components/src/components/index.ts
packages/components/src/components/typography/Typography.tsx
packages/components/src/components/validation/Validation.tsx
packages/styles/.circleci/config.yml

I was looking at upgrading SFE-RTC to React 18 and one thing done is that `children` is not a built in prop anymore. This React 18 proofs UIToolkit.

React 18 proof types

---

packages/components/src/components/drawer/Drawer.tsx
packages/components/src/components/modal/Modal.tsx

Ever since Symphony switched to loading the client and extensions over Startpage, the rendering of font icons breaks sometimes. In SFE-RTC we replaced all usage of font icons with SVG icons. This is a remaining case for us where the X in closing the modal can break.
This does not affect only SFE-RTC but will fix things for all extensions using `Modal`.
https://perzoinc.atlassian.net/browse/RTC-14251

Use SVG Icon instead for Drawer and Modal

---

packages/components/spec/components/time-picker/TimePicker.spec.tsx
packages/components/spec/components/toast/Toast.spec.tsx
packages/components/src/components/dropdown/CustomRender.tsx
packages/components/src/components/toast/Toast.tsx
packages/styles/.circleci/config.yml
packages/styles/src/components/atoms/_toast.scss
packages/styles/src/uitoolkit-components/_select.scss

As previously discussed font icon rendering started breaking at times since Startpage was introduced and the solution has been to switch to SVGIcons which is a more modern way of doing it. This fixes the `Dropdown` component.

RTC-14706 - Switch Dropdown icons to be SVGIcons

---

packages/components/tsconfig.json

`2017` is the version used in SFE-Lite and I think the null coalescing or optional chaining is what causes the problem when SFE-Lite tries importing.

Was using too modern target in tsconfig

---

packages/components/README.md
packages/components/docs/getting-started.md
packages/components/src/components/modal/Modal.tsx
packages/styles/README.md
packages/styles/src/components/atoms/_dialog.scss

Component styles are not forwarded when using styled components in popped out windows.
Hopefully, using SASS styles will fix the issue.
https://perzoinc.atlassian.net/browse/RTC-14800
Looks the same:
Hover:

RTC-14800 Remove styled components for popped out window styles forwarding

---

package.json
packages/components/package.json
packages/styles/package.json

When SFE-Lite imports UI Toolkit, the minimum specified Node engine needs to be met. SFE-Lite runs on 14 and this was set to 16, so lowering in this PR.
The reason it was set to 16 was because in order to run Storybook, 16 is the minimum version required, but SFE-Lite does not run Storybook, it just imports the package.

RTC-14883 - Set minimum required Node version to 14 instead of 16

---

packages/components/src/components/tooltip/Tooltip.tsx

Accidentally added a semicolon in the React render.

Remove extra semicolon

---

packages/components/spec/components/modal/Modal.spec.tsx
packages/components/src/components/modal/Modal.tsx
packages/components/stories/Modal.stories.tsx

Manage the trap of focusing on the modal component.
The added logic is quite simple, and solves simple scenarios. I'll add complexity later if more complex situations come up.
This behavior is set by default, because this is the default behavior recommended by accessibility guidelines. 
>When a modal element is displayed, focus should be placed in the modal. Focus needs to be "trapped" inside the modal when it is visible, until it is dismissed.
(Source: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-modal)
However, it can be deactivated with `focusTrapEnabled={false}`.
[JIRA_Ticket](https://perzoinc.atlassian.net/browse/BYC-1304)
https://github.com/user-attachments/assets/a534b614-9bc6-4f53-990c-505441f273d2

BYC-1304 Handle focus trap on the Modal component

---

packages/components/src/components/modal/Modal.tsx

Restore the focus to original position after closing modal
[C2-24240](https://perzoinc.atlassian.net/browse/C2-24240)
https://github.com/user-attachments/assets/fc879823-27a3-4baa-b7e7-786c9c7f1ecc
[C2-24240]: https://perzoinc.atlassian.net/browse/C2-24240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

C2-24240 Restore focus when closing the modal

---

packages/styles/src/components/atoms/_banner.scss

Banner: close button reset

---

packages/components/spec/components/nav/Nav.spec.tsx
packages/components/src/components/nav/Nav.tsx
packages/components/stories/Nav.stories.tsx
packages/styles/src/components/atoms/_nav.scss
packages/styles/stories/navigation.stories.js

Nav was based on a nav, but used as a tablist. I changed it to be now a tablist and to be accessible following tab pattern:
https://www.w3.org/WAI/ARIA/apg/patterns/tabs/
https://perzoinc.atlassian.net/browse/BYC-1470
https://github.com/user-attachments/assets/17f6a43b-aa10-4e16-a594-106a267cfb31

BYC-1470 make nav component accessible

---

packages/components/src/components/modal/Modal.tsx

**Fix**: In one particular case, when content changed dynamically with a `tabIndex = -1` added to an element that could have the focus, then focus-trap set the focus on this element without taking into account the tabIndex of -1.
https://perzoinc.atlassian.net/browse/BYC-1470

BYC-1470 Fix focus-trap with tab-index

---

packages/components/src/components/button/Button.tsx

Update Button typing to use React.FC 
also removed the PropsType and DefaultProps in favor of native TypeScript solution

Update Button typing to use React.FC

---

packages/components/spec/components/date-picker/DatePicker.spec.tsx
packages/components/spec/components/date-picker/Header.spec.tsx
packages/components/src/components/date-picker/DatePicker.tsx
packages/components/src/components/date-picker/sub-component/DayPicker.tsx
packages/components/src/components/date-picker/sub-component/Header.tsx
packages/styles/src/uitoolkit-components/_date-picker.scss

- Add tooltip for preYear, preMonth, nextYear, nextMonth button
- When calendar popped-up, focus is moving to the current date
- SR is announcing that filed has calendar pop-up
[C2-24993](https://perzoinc.atlassian.net/browse/C2-24993)
[C2-24993]: https://perzoinc.atlassian.net/browse/C2-24993?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

C2-24993-uitoolkit: Date picker not accessible

---

packages/components/src/components/dropdown/CustomRender.tsx
packages/components/src/components/dropdown/Dropdown.tsx

Add aria-label in dropdown as htmlFor in react labels link the label with the dropdown input
[CES-20069](https://perzoinc.atlassian.net/browse/CES-20069)
---
https://github.com/user-attachments/assets/279d49b7-c65c-4cee-96dc-c12f21f674dd
[CES-20069]: https://perzoinc.atlassian.net/browse/CES-20069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CES-20069] Add aria-label in dropdown

---

packages/components/package.json
packages/components/src/components/input/InputDecorator.tsx
packages/components/src/components/input/TextComponent.tsx
packages/components/src/components/selection/SelectionInput.tsx
packages/components/src/core/hoc/StylesInjection.tsx
yarn.lock

https://perzoinc.atlassian.net/browse/RTC-15444
`shortid` is deprecated and `nanoid` is preferred. Changing this as we're implementing full Snyk scanning in SFE-RTC and this comes up as a security vulnerability.

RTC-15444 - Replace shortid with nanoid

---

packages/components/package.json
packages/components/src/components/input/InputDecorator.tsx
packages/components/src/components/input/TextComponent.tsx
packages/components/src/components/selection/SelectionInput.tsx
packages/components/src/core/hoc/StylesInjection.tsx
yarn.lock

**Replace `nanoid` by `uuid`**
`nanoid` is causing unit test failures in projects using ui-toolkit.
- remove `nanoid` dependency
- add `uuid` dependency (no snyk issue)
- replace `nanoid()` by `uuidv4()`
- replace `customAlphabet()` by a custom function using `uuidv4()`

Replace `nanoid` by `uuid`

---

packages/components/package.json
yarn.lock

This commit replaces `uuid@11.1.0` by `uuid@8.3.2`, aligned with the one used in C2.
`uuid@11.1.0` is using modern syntax that is not supported by all the UI-Toolkit consumers.

Use `uuid@^8.3.2`

---

packages/components/src/core/hoc/StylesInjection.tsx

https://perzoinc.atlassian.net/browse/RTC-15488
See - https://emotion.sh/docs/@emotion/cache#stylisplugins. I think the default `prefixer` is unnecessary and when I'm doing some CSS work it adds a lot of noise inspecting elements as each property is triplicated.

RTC-15488 - Set plugins array to empty so it doesn't include unnecessary prefixer

---

packages/components/spec/components/date-time/DateTime.spec.tsx
packages/components/src/components/date-time/DateTime.tsx
packages/components/src/components/date-time/index.ts
packages/components/src/components/date-time/interfaces.ts
packages/components/src/components/date-time/utils.ts
packages/components/src/components/index.ts
packages/components/stories/DateTime.stories.tsx

[UPL-151](https://perzoinc.atlassian.net/browse/UPL-151): `DateTime` component
New `DateTime` component allowing to display a date or a time (or both) according to the provided settings. By default, renders date and time using the browser locale formatting.
Properties:
- `date`: the date information to display (ISO string or Date)
- `format`: one of:
- `DATE_TIME` (default): renders the date and time (i.e. '12/31/2024 10:29 AM')
- `DATE`: renders the date (i.e. '12/31/2024')
- `TIME`: renders the time (i.e. '10:29 AM')
- `TIME_SECS`: renders the time with seconds (i.e. '10:29:47 AM')
- `locale`: the locale to use for date and time formatting (i.e. 'fr-FR') - default is the browser locale
- `show12HourTime`: whether to display the time in 12-hour format (i.e. '05:29 PM')
- `dateFormat`: …

UPL-151: `DateTime` component

---

packages/components/src/components/dropdown-menu/DropdownMenu.tsx

Although `menu-item` role seems to be recognized by voice over on Mac, it is not recognized on Windows with tools like NVDA. This PR aims to fix it. by using `menuitem` role instead (without hyphen)
[CES-22621](https://perzoinc.atlassian.net/browse/CES-22621)
[CES-22621]: https://perzoinc.atlassian.net/browse/CES-22621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CES-22621 - Fix menuitem role for all screen reader

---

packages/components/src/components/date-picker/DatePicker.tsx
packages/components/src/components/date-picker/sub-component/DayPicker.tsx
packages/components/src/components/date-picker/sub-component/Header.tsx
packages/components/src/components/date-picker/utils/dateUtils.tsx
packages/styles/src/uitoolkit-components/_date-picker.scss

Restructure the html tree so that the days of the month are rendered correctly with the corresponding row and coloumn.
[C2-24526](https://perzoinc.atlassian.net/browse/C2-24526)
[C2-24526]: https://perzoinc.atlassian.net/browse/C2-24526?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix issue about SR read incorrect row and column when focusing to date in DatePicker
