SymphonyPlatformSolutions/symphony-ui-toolkit

.eslintrc.js, .prettierrc, .storybook/config.js, .storybook/main.js, babel.config.js, package.json, spec/components/button/Button.spec.jsx, spec/components/input/Input.spec.tsx, spec/core/validators.spec.ts, src/components/button/index.ts, src/components/index.ts, src/components/input/Input.tsx, src/components/input/index.ts, src/core/validators/validators.ts, src/index.ts, stories/Button.stories.tsx, stories/Input.stories.tsx, stories/stories.scss, tsconfig.json, yarn.lock
=> APP-2699 - Input component with validation

.circleci/config.yml, spec/components/time-picker/timeUtils.spec.tsx, spec/components/tooltip/Tooltip.spec.tsx, src/components/dropdown/CustomRender.tsx, src/components/dropdown/Dropdown.tsx, src/components/time-picker/TimePicker.tsx, src/components/time-picker/utils/timeUtils.tsx
**Jira ticket:**
https://perzoinc.atlassian.net/browse/APP-3820
**Changes:**
- Dropdown: Add onKeyUp attribute
- TimePicker: 
- Improve more robust next focus selection code
- Autofill separator when typing
- When typing jump automatically to next value
---
**Demo: Tab/Shift tab**
**Demo: Auto fill the input with the delimiters**
**Demo: Auto jump to next field**
=> APP-3820 Jump automatically to next value

package.json, src/components/avatar/index.ts, src/components/index.ts, stories/Avatar.stories.tsx, yarn.lock
- Exported avatar component as Interface
- Added default avatar on docs
- Bumped UIToolkit Styles
[Jira ticket](https://perzoinc.atlassian.net/browse/APP-3353)
=>  APP-3353 Avatar improvements

package.json, src/components/dropdown/Dropdown.tsx, yarn.lock
- Added focus state on the dropdown. 
- Added blurInputOnSelect prop
Before:
Fix:
=> APP-3984 Focus state on dropdown

package.json, stories/Avatar.stories.tsx, yarn.lock
- Avatar with text and Avatar with Icon displayed correctly without defining fontsize
- Bump UIToolkit styles
[Jira ticket](https://perzoinc.atlassian.net/browse/APP-3353)
=> APP-3353 Avatar with text centered

package.json, yarn.lock
=> APP-3737 Bumped UIToolkit Styles

src/components/input/TextComponent.tsx
- fix warning "unknown handler" with onValidationChanged prop
- fix show/hide button: removed display none
=> EIS-2597 - TextComponent fixes

spec/components/time-picker/TimePicker.spec.tsx
https://perzoinc.atlassian.net/browse/APP-4020
**Changes**
- Improve unit tests of Timepicker component
**Before:**
**After:**
=> APP-4020 Improve unit tests of Timepicker component

spec/components/date-picker/DatePicker.spec.tsx, spec/components/input/TextComponent.spec.tsx, spec/components/label-tooltip-decorator/LabelTooltipDecorator.spec.tsx, spec/components/time-picker/TimePicker.spec.tsx, src/components/date-picker/DatePicker.tsx, src/components/dropdown/Dropdown.tsx, src/components/input/TextComponent.tsx, src/components/label-tooltip-decorator/LabelTooltipDecorator.tsx, src/components/time-picker/TimePicker.tsx, stories/DatePicker.stories.tsx, stories/Dropdown.stories.tsx, stories/TextArea.stories.tsx, stories/TextField.stories.tsx, stories/TimePicker.stories.tsx
if showRequired is set, the style tk-label--required will be applied
components:
- DatePicker,
- TextComponent (TextField/TextArea)
- TimePicker,
- Dropdown
=> EIS-2792 - showRequired prop added

spec/components/crop-content/CropContent.spec.tsx, spec/components/expandable-card/ExpandableCard.spec.tsx, src/components/crop-content/CropContent.tsx, src/components/expandable-card/ExpandableCard.tsx, stories/CropContent.stories.tsx, stories/ExpandableCard.stories.tsx
Backport of https://github.com/SymphonyPlatformSolutions/symphony-bdk-ui-toolkit-components/pull/186
=> APP-3943 - cherry-pick c56006c77b71096036e83f56467397c98e616092

spec/components/selection/Switch.spec.tsx, src/components/index.ts, src/components/selection/SelectionInput.tsx, src/components/selection/SelectionStatus.tsx, src/components/selection/SelectionTypes.tsx, src/components/selection/Switch.tsx, src/components/selection/index.ts, stories/Switch.stories.tsx
EIS-2819: Add Switch component
- Added the Switch component, which is an alternative checkbox display
- Added a new story (based on the checkbox one)
- Added related tests
- Added Switch type in SelectionTypes enum
**EDIT**
- Added SelectionStatus.SWITCHED and SelectionStatus.UNSWITCHED
- Mixed status test removed
- Replaced the term 'checkbox' by 'switch' in the tests
-----
https://user-images.githubusercontent.com/66251236/114895786-11c94300-9e10-11eb-95fa-9966be6d9ece.mov
-----
- PR ui-toolkit-styles: [https://github.com/SymphonyPlatformSolutions/symphony-bdk-ui-toolkit-styles/pull/81](https://github.com/SymphonyPlatformSolutions/symphony-bdk-ui-toolkit-styles/pull/81)
- Jira ticket: [https://perzoinc.atlassian.net/browse/EIS-2819](https://perzoinc.atlassian.net/browse/EIS-2819)
- Doc: …
=> EIS-2819: Add Switch component

package.json, yarn.lock
https://perzoinc.atlassian.net/browse/APP-4096
=> APP-4096 Bump UI-Toolkit-Styles v1.5.0

spec/components/toast/Toast.spec.tsx, src/components/index.ts, src/components/toast/Toast.tsx, src/components/toast/index.ts, stories/Toast.stories.tsx
- https://perzoinc.atlassian.net/wiki/spaces/DevX/pages/1930300829/Toast - Proposal
- https://perzoinc.atlassian.net/browse/APP-4097 - Ticket
- https://www.figma.com/file/V0VKw74594EyCKHwqYk6LV/%E2%9D%96-SDS-Component-Library - Design for Toast component
- ui-toolkit-styles PR - https://github.com/SymphonyPlatformSolutions/symphony-bdk-ui-toolkit-styles/pull/87
=> APP-4097 - Toast component

spec/components/date-picker/DatePicker.spec.tsx, spec/components/date-picker/DayPicker.spec.tsx, spec/components/date-picker/Header.spec.tsx, src/components/date-picker/DatePicker.tsx, src/components/date-picker/sub-component/DayPicker.tsx
https://perzoinc.atlassian.net/browse/APP-3449
- Add new unit tests using testing library
- Also do a minor fix on the Day Picker :) (thank you unit tests!)
=> APP-3449 - test(datePicker/dayPicker): increase ut coverage

package.json, src/components/dropdown/CustomRender.tsx, src/components/dropdown/Dropdown.tsx, stories/Dropdown.stories.tsx, yarn.lock
- Added maxSelectHeight prop to Dropdown
- Handle long description display of multiselect options
- Added example on storybook
[Jira ticket](https://perzoinc.atlassian.net/browse/APP-3873)
=> APP-3873 Added maxSelectHeight prop to Dropdown

stories/Dropdown.stories.tsx
- Align storybook example
[Jira-ticket](https://perzoinc.atlassian.net/browse/APP-3873)
=> APP-3873 Remame prop

package.json, stories/Card.stories.tsx, stories/Loader.stories.tsx, yarn.lock
-  Remove scale from storybook examples
-  Bumped UIToolkit Styles
=> APP-4073 Remove scale from storybook examples

spec/components/dropdown/Dropdown.spec.tsx
Adding a unit test for the new prop
=> APP-3931 test(dropdown): add a unit test related to the nested mode

spec/components/modal/Modal.spec.tsx, src/components/modal/Modal.tsx, stories/Modal.stories.tsx
https://perzoinc.atlassian.net/browse/APP-3965
**Change**
Close Modal on 'ESC'
=> APP-3965 Close Modal on 'ESC'

package.json, yarn.lock
https://perzoinc.atlassian.net/browse/APP-3965
**Changes**
Bump UI-Toolkit-Styles v1.5.0-rc.5
=> APP-3965_BUMP Bump UI-Toolkit-Style

spec/components/dropdown/Dropdown.spec.tsx, src/components/dropdown/CustomRender.tsx
-  Focus at the top of a the dropdown list when the user press the 'home' key
- Added UT
[Jira-ticket](https://perzoinc.atlassian.net/browse/APP-4131)
=> APP-4131 Focus at the top of a the dropdown list when the user press the 'home' key

package.json, yarn.lock
-  Bumped UIToolkit Styles
[Jira-ticket](https://perzoinc.atlassian.net/browse/APP-4150)
=> APP-4150 Bumped UIToolkit Styles

spec/components/dropdown/Dropdown.spec.tsx, src/components/dropdown/CustomRender.tsx, src/components/dropdown/Dropdown.tsx, src/components/dropdown/interfaces.ts, stories/Dropdown.stories.tsx
- Added loading Options dropdown
- Add examples to storybook 
[Jira-ticket](https://perzoinc.atlassian.net/browse/APP-3872)
=> APP-3872 Added loading options to Dropdown

stories/Typography.stories.tsx, stories/stories.scss
- Update typography use cases on storybook
[Jira-ticket](https://perzoinc.atlassian.net/browse/APP-4129)
=> APP-4129 Update typography use cases on storybook

package.json, yarn.lock
https://perzoinc.atlassian.net/browse/APP-4197
**Changes**
Bump UI-Toolkit-Styles v2.0.0
=> APP-4197 Bump UI-Toolkit-Styles v2.0.0

stories/Typography.stories.tsx, stories/stories.scss
- Update Typography storybook example
[Jira-ticket](https://perzoinc.atlassian.net/browse/APP-4129)
=> APP-4129 Update Typography storybook example

src/components/dropdown/Dropdown.tsx
- Expose menuPlacement prop on Dropdown
[Jira-ticket](https://perzoinc.atlassian.net/browse/APP-4188)
=> APP-4188 Expose menuPlacement prop on Dropdown

package.json, yarn.lock
https://perzoinc.atlassian.net/browse/APP-4254
**Changes**
Bump UI-Toolkit-Styles v2.1.0
=> APP-4254 Bump UI-Toolkit-Styles v2.1.0

spec/components/dropdown/Dropdown.spec.tsx
- Added UT when providing a list to 'defaultOptions' prop
- Added UT when filtering  'asyncOptions'
=> APP-4249 Increase test coverage async dropdown

package.json, yarn.lock
https://perzoinc.atlassian.net/browse/APP-4195
**Changes**
Bump UI-Toolkit-Styles [v2.2.0-rc.0](https://github.com/SymphonyPlatformSolutions/symphony-bdk-ui-toolkit-styles/releases/tag/v2.2.0-rc.0)
=> APP-4195 Bump UI-Toolkit-Styles v2.2.0-rc.0

LICENSE
https://perzoinc.atlassian.net/browse/APP-4202
**Change:**
- Add Apache 2.0 license
I only replaced in the template:
`Copyright [yyyy] [name of copyright owner]`
by
`Copyright 2021 Symphony Communication Services, LLC`
(as it is the copyright written on https://symphony.com/)
=> APP-4202 Add a License

spec/components/tooltip/Tooltip.spec.tsx, src/components/tooltip/Tooltip.tsx, stories/Tooltip.stories.tsx
We want to add a delay before displaying the Tooltip on Hover
=> feat: add configurable delay to display the Tooltip

stories/Checkbox.stories.tsx
https://perzoinc.atlassian.net/browse/APP-4316
**Changes**
Update description in Storybook Checkbox story
=> APP-4316 Update description in Storybook Checkbox story

spec/components/badge/Badge.spec.tsx, src/components/badge/Badge.tsx, src/components/badge/index.ts, src/components/index.ts, stories/Badge.stories.tsx
Styles PR: https://github.com/SymphonyPlatformSolutions/symphony-bdk-ui-toolkit-styles/pull/111
https://www.figma.com/file/V0VKw74594EyCKHwqYk6LV/%E2%9D%96-SDS-Core-Component-Library?node-id=4394%3A60463
=> SYM-4424: Badge component

package.json, yarn.lock
https://perzoinc.atlassian.net/browse/APP-4334
**Changes**
Use UI-Toolkit Styles v2.3.0
=> APP-4334 Use UI-Toolkit Styles v2.3.0

spec/components/avatar/Avatar.spec.tsx, src/components/avatar/Avatar.tsx
=> APP-4346 - fix(Avatar): Rename badge class

package.json, yarn.lock
https://perzoinc.atlassian.net/browse/APP-4353
**Change**
Bump UIToolkit Styles v2.3.1
=> APP-4353 Bump UIToolkit Styles v2.3.1

src/components/crop-content/CropContent.tsx
- listening for attribute change and debounce size recalc
https://user-images.githubusercontent.com/63653674/126347982-febf7102-90d4-421f-807b-92bf13616910.mp4
=> APP-4219 - Fix resize in cropcontent

src/components/badge/Badge.tsx, src/components/badge/interfaces.ts, stories/Badge.stories.tsx
- Add size variants to the Badge (size, medium)
=> feat: badge sizes

spec/components/text-ellipsis/TextEllipsis.spec.tsx, src/components/dropdown/CustomRender.tsx, src/components/text-ellipsis/TextEllipsis.tsx, stories/Dropdown.stories.tsx
- Added support for className in TextEllipsis
- Added initial support for data-testid to Dropdown component. This needs to be worked on more so all props can be passed correctly but it was a quite tricky component to navigate so I think this is an okay start.
=> RTC-10351 - Adding optional className to TextEllipsis

package.json, yarn.lock
Changelog https://github.com/SymphonyPlatformSolutions/symphony-bdk-ui-toolkit-styles/releases/tag/v2.3.2
=> chore(styles): Bump styles to 2.3.2

package.json, spec/components/text-ellipsis/TextEllipsis.spec.tsx, src/components/text-ellipsis/TextEllipsis.tsx, yarn.lock
- Added a unit test to test webLineClamp property
- Removed unnecessary class.
=> Fixing TextEllipsis component

spec/core/validators/validators.spec.tsx, src/core/validators/validators.ts, stories/Validation.stories.tsx
https://perzoinc.atlassian.net/browse/APP-4391
Improve EmptyString validator to detect blank value
=> APP-4391 Improve EmptyString validator

src/components/dropdown/CustomRender.tsx
- Added keyboard navigation on close icon dropdown
- Added aria label 
Demo:
https://user-images.githubusercontent.com/68587873/129881619-5a71e82c-2d68-44d0-b369-5e658d3c7686.mp4
=> APP-4343 Added keyboard navigation on close icon dropdown

package.json, yarn.lock
https://perzoinc.atlassian.net/browse/APP-4437
**Changes**
Bump UI-Toolkit-Styles v2.4.0
=> APP-4437 Bump UI-Toolkit-Styles v2.4.0

src/components/dropdown/CustomRender.tsx, src/components/icon/Icon.tsx
- Added keyboard event to dropdown icon
https://user-images.githubusercontent.com/68587873/131303249-2c7bf514-9002-41e4-97aa-3e144cfdead6.mp4
=> APP-4343 Added keyboard event to dropdown icon

package.json, yarn.lock
https://perzoinc.atlassian.net/browse/APP-4487
**Changes**
Bump UI-Toolkit Styles v2.5.0
=> APP-4487 Bump UI-Toolkit-Styles v2.5.0

package.json, src/components/input/InputDecorator.tsx, src/components/input/TextComponent.tsx, src/components/selection/SelectionInput.tsx, src/core/hoc/StylesInjection.tsx, yarn.lock
Let StylesInjection create the id for @emotion/cache instead of the one implementing it.
=> RTC-11327 - Let StylesInjection create the id for @emotion/cache

spec/core/validators/validators.spec.tsx, src/core/validators/validators.ts, stories/Validation.stories.tsx
https://perzoinc.atlassian.net/browse/APP-4474
- Improve the Required validator
- Deprecate EmptyString validator
- Add non regression test
Have a look at the validator.spec.tsx
=> APP-4474 - Deprecate EmptyString and improve Required validator

package.json, yarn.lock
https://perzoinc.atlassian.net/browse/APP-4505
**Changes**
Bump UI-Toolkit Styles 2.6.0
=> APP-4505 Bump UI-Toolkit Styles 2.6.0

package.json, src/components/input/InputDecorator.tsx, src/components/input/TextComponent.tsx, src/components/selection/SelectionInput.tsx, src/core/hoc/StylesInjection.tsx, yarn.lock
https://perzoinc.atlassian.net/browse/APP-4518
**Changes**
Cherry-pick commits from PR #299
**Related PR**
#299
=> APP-4518 [master] Temporarily use shortId instead of nanoid because nanoid is not transpiled for IE11

spec/components/button/Button.spec.tsx, src/components/button/Button.tsx, stories/Button.stories.tsx
=> APP-4455 new btn component

spec/components/drawer/Drawer.spec.tsx, src/components/drawer/Drawer.tsx, src/components/drawer/index.ts, src/components/drawer/interfaces.ts, src/components/index.ts, stories/Drawer.stories.tsx
Component interface: https://perzoinc.atlassian.net/wiki/spaces/DevX/pages/2227241175/Drawer
Figma design for the original MS component: https://www.figma.com/file/tdHdGPWz9wzdTH4MBHnmGN/MS-Components?node-id=2617%3A6351
Storybook:
=> Drawer component

.storybook/main.js, package.json, src/components/time-picker/TimePicker.tsx, src/components/time-picker/interfaces.ts, src/components/time-picker/utils/timeUtils.tsx, src/core/hoc/StylesInjection.tsx, stories/Avatar.stories.tsx, stories/Badge.stories.tsx, stories/Button.stories.tsx, stories/Card.stories.tsx, stories/Checkbox.stories.tsx, stories/CropContent.stories.tsx, stories/DropdownMenu.stories.tsx, stories/ExpandableCard.stories.tsx, stories/InputDecorator.stories.tsx, stories/Link.stories.tsx, stories/Loader.stories.tsx, stories/Radio.stories.tsx, stories/Switch.stories.tsx, stories/TextArea.stories.tsx, stories/TextField.stories.tsx, stories/TimePicker.stories.tsx, stories/Typography.stories.tsx, yarn.lock
https://perzoinc.atlassian.net/browse/APP-4531
**Changes**
Add missing dependency to 'react-docgen-typescript-loader' package because the descriptions were not correctly loaded from our components.
- Update TimePicker description:
- Code cleanup in other stories
**Demo without the fix**
**Demo with the fix**
**Demo without the fix**
**Demo with the fix**
=> APP-4531 Add missing descriptions in Docs tab of StoryBook

spec/components/button/Button.spec.tsx, src/components/button/Button.tsx, stories/Button.stories.tsx, stories/stories.scss
- Loading button fixed size
- Right icon well displayed
- Added button role
=> APP-4546 Bug fixes

.eslintrc.js, spec/core/validators/validators.spec.tsx, src/core/validators/validators.ts
https://perzoinc.atlassian.net/browse/APP-4313
Add validator for email
=> APP-4313 - Add Email validator

tsconfig.json
Fix build package by removing new templates stories file, otherwise, the content of the built package contains 'src' directory.
=> APP-4552 Fix built by removing templates stories

package.json, yarn.lock
https://perzoinc.atlassian.net/browse/APP-4655
**Changes**
Bump UI-Toolkit Styles v2.9.0
=> APP-4655 Bump UI-Toolkit Styles v2.9.0

spec/components/validation/Validation.spec.tsx, spec/core/validators/validators.spec.tsx, src/components/validation/Validation.tsx, src/core/validators/validators.ts, stories/Validation.stories.tsx
- Added maxLength validator
- Update UT
- Add example on Storybook
- On Text field:
- Several validators:
- On dropdown
[Jira ticket](https://perzoinc.atlassian.net/browse/APP-4594)
=> APP-4594 Added maxLength validator

spec/components/date-picker/DatePicker.spec.tsx, src/components/date-picker/DatePicker.tsx
Allow keyboard navigation but not the one that could potentially scrol
l
=> APP-4551 - Fix keyboard navigation when menuShouldBlockScroll

spec/core/validators/validators.spec.tsx, src/core/validators/validators.ts
- Fix required validator to Dropdown
- Increase test cases to Input validators
[Jira-ticket](https://perzoinc.atlassian.net/browse/APP-4672)
=> APP-4672 Improve input validator

stories/DropdownMenu.stories.tsx, stories/styles/dropdownMenu.stories.css
- Use classes from UItoolkitStyles
=> APP-4695 Use classes from UItoolkitStyles

stories/DropdownMenu.stories.tsx
=> docs(dropdown-menu): improve documentation

stories/Toast.stories.tsx
=> feat: improve Toast stories

stories/Banner.stories.tsx
Improving Banner component docs (all stories).
Sample before:
Sample after:
=> feat: improve Banner stories

stories/InputDecorator.stories.tsx
Improving InputDecorator component docs (all stories).
Sample before:
Sample after:
=> feat: improve docs for InputDecorator component

spec/components/crop-content/CropContent.spec.tsx, src/components/crop-content/CropContent.tsx, stories/CropContent.stories.tsx
https://perzoinc.atlassian.net/browse/APP-4609
- Add a control of the collapse logic from external
- Refine the storybook doc
- Add a storybook example
=> APP-4609 feat(crop content): add collapsed control

src/components/crop-content/CropContent.tsx, stories/CropContent.stories.tsx
- A some explanation in the doc
- Remove unnecessary setState when controlled
=> APP-4609 improve the doc and optimize a bit the code

package.json, yarn.lock
=> APP-4712 Bump UI-Toolkit-Styles 2.11.0

src/components/dropdown/Dropdown.tsx, src/components/dropdown/interfaces.ts, stories/Dropdown.stories.tsx
https://perzoinc.atlassian.net/browse/APP-4689
Override jss
PR Styles: https://github.com/SymphonyPlatformSolutions/symphony-bdk-ui-toolkit-styles/pull/179
=> APP-4689 feat(dropdown): add small styles for dropdown

package.json, yarn.lock
- Bumped UITtoolkit Styles v2.11.1
=> APP-4692 Bumped UITtoolkit Styles v2.11.1

src/components/date-picker/DatePicker.tsx, src/components/dropdown/Dropdown.tsx, src/components/dropdown/interfaces.ts, src/components/input/TextComponent.tsx, src/components/time-picker/TimePicker.tsx, src/components/time-picker/interfaces.ts, stories/DatePicker.stories.tsx, stories/Dropdown.stories.tsx, stories/TextArea.stories.tsx, stories/TextField.stories.tsx, stories/TimePicker.stories.tsx
- Added helper text to input group
[JIra_ticket](https://perzoinc.atlassian.net/browse/APP-4709)
=> APP-4709 Added helper text to input group

spec/core/validators/validators.spec.tsx, src/components/index.ts, src/core/validators/validators.ts, stories/Validation.stories.tsx
- checks against the JavaScript URL() constructor for validity
- added Storybook stories to illustrate both Url and Email validation cases
- set Validators as a named export for ease of use
https://user-images.githubusercontent.com/75674576/145537481-89d4bac2-a382-490d-a1d2-66fe846dcc08.mov
Immediate use case: EIS integrations need URL validation on some fields in existing integrations.
Jira ticket: https://perzoinc.atlassian.net/browse/EIS-3457
=> EIS-3457: URL validation

.storybook/main.js, .storybook/preview.js, package.json, spec/components/date-picker/DatePicker.spec.tsx, src/components/date-picker/DatePicker.tsx, src/components/dropdown/CustomRender.tsx, src/components/dropdown/Dropdown.tsx, stories/Dropdown.stories.tsx, stories/TextField.stories.tsx, yarn.lock
https://perzoinc.atlassian.net/browse/APP-4707
https://perzoinc.atlassian.net/browse/APP-4586
https://perzoinc.atlassian.net/browse/APP-4696
https://perzoinc.atlassian.net/browse/APP-4414
- Add tk-input__right-decorators__clickable (naming maybe too long, open for suggestion if any)
- Date Picker use the rightDecorators feature
- Right decorators automatically centers the `i` tag (the icons)
- Fix button focus
- Adjust some Dropdown style
- Add storybook-addon-themes
Styles https://github.com/SymphonyPlatformSolutions/symphony-bdk-ui-toolkit-styles/pull/185
Date Picker
Time Picker: THe icon is not clickable anymore
Button fix focus
=> APP-4729 APP-4707 APP-4586 APP-4414 - Time and Date Picker (field) to follow SDS, and fix button focus

src/components/date-picker/DatePicker.tsx, src/components/dropdown/interfaces.ts, src/components/time-picker/interfaces.ts
https://perzoinc.atlassian.net/browse/APP-4755
**Related PR:**  #366
=> APP-4755 Fix overlapping interfaces for the value property

spec/core/validators/validators.spec.tsx, src/core/validators/validators.ts, stories/Validation.stories.tsx
=> APP-4735 Fix: datePicker required error displayed

src/components/icon/Icon.tsx, src/components/toast/Toast.tsx, stories/Icons.stories.tsx, stories/Validation.stories.tsx
- APP-4647 Added Icon types
[Jira-ticket](https://perzoinc.atlassian.net/browse/APP-4647)
=> APP-4751 Added Icon types

spec/core/validators/validators.spec.tsx, src/core/validators/validators.ts
- APP-4735 Validate required date
=> APP-4735 Validate required date

package.json, yarn.lock
[APP-4775
](https://perzoinc.atlassian.net/browse/APP-4775)
**Changes**
Bump UI-Toolkit Styles v2.11.2
=> APP-4775 Bump UI-Toolkit Styles v2.11.2

src/components/dropdown/interfaces.ts
=> Fix: Omit default value

package.json, src/components/dropdown/CustomRender.tsx, src/components/dropdown/Dropdown.tsx, stories/Dropdown.stories.tsx, yarn.lock
Use our style instead https://github.com/SymphonyPlatformSolutions/symphony-bdk-ui-toolkit-styles/pull/194
=> APP-4771 - fix(dropdown): remove margin around a token from the lib

stories/Dropdown.stories.tsx, stories/TextField.stories.tsx, stories/Tooltip.stories.tsx
- Improve Textfield storybook example
- Add tooltip variant example
[JIRA_Ticket](https://perzoinc.atlassian.net/browse/APP-4887)
=> [APP-4787] [APP-4792] Improve input story page

jest.config.js, spec/core/validators/validators.spec.tsx, src/components/icon/Icon.tsx, src/components/index.ts, src/components/input/TextComponent.tsx, src/core/validators/validators.ts, stories/InputDecorator.stories.tsx
remove deprecated func and prop + export TkIcon
=> feat(deprecation): remove deprecated func and prop + export TkIcon

.gitignore, packages/styles/.circleci/config.yml
Use UI-TK AWS Configuration
(Also ignore files from UI-TK Components and UI-TK Styles, otherwise a git pull after the merge will no longer ignore the locally generated files)
[APP-4664](https://perzoinc.atlassian.net/browse/APP-4664)
=> APP-4664 Use UI-TK AWS Configuration

packages/styles/.circleci/config.yml
Fix AWS Region
[APP-4664](https://perzoinc.atlassian.net/browse/APP-4664)
=> APP-4664 Fix AWS config (2)

packages/styles/.circleci/config.yml
Add AWS conf in command arguments
[APP-4664](https://perzoinc.atlassian.net/browse/APP-4664)
=> APP-4664 Add aws conf in command arguments

packages/components/.circleci/config.yml, packages/styles/.circleci/config.yml
Use aws-cli to configure AWS profiles
[APP-4664](https://perzoinc.atlassian.net/browse/APP-4664)
=> APP-4664 Use aws-cli to configure AWS profiles

.github/dependabot.yml
Daily update of UI-Toolkit dependencies
[APP-4525](https://perzoinc.atlassian.net/browse/APP-4525)
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates
=> APP-4525 Daily update of UI-Toolkit dependencies

.github/dependabot.yml
Create only 1 PR to update dependencies
[APP-4525](https://perzoinc.atlassian.net/browse/APP-4525)
=> APP-4525 Create only 1 PR to update dependencies

packages/components/src/components/time-picker/TimePicker.tsx
The selectedOption was set to null
Fix access to hours, minutes, seconds since the recent refactor
=> Time Picker - Fix null selectedOption

packages/components/src/components/dropdown/Dropdown.tsx
Add robustness if the option is null
=> APP-4946 Add robustness if the option is null

packages/components/src/components/time-picker/TimePicker.tsx, packages/components/src/components/time-picker/utils/Time.tsx, packages/components/src/components/time-picker/utils/timeUtils.tsx, yarn.lock
https://perzoinc.atlassian.net/browse/APP-4937
**Changes**
Fix: TimePicker - Android & iOS - Crash when selecting a value
=> APP-4937 Fix: TimePicker - Crash when selecting a value on mobile

packages/components/stories/Validation.stories.tsx
Original problem state that the value of the TextField cannot be edited
This is not an issue, but just a documentation to improve to be able to change the value of the TextField
This is not a specific "iOS/Android issue"
https://perzoinc.atlassian.net/browse/APP-4938
Gif from Safari
=> APP-4938 Improve documentation

packages/components/src/components/button/Button.tsx
Same change as the previous modal PR.
=> Allow button to accept html button props

packages/components/spec/components/time-picker/TimePicker.spec.tsx, packages/components/src/components/time-picker/TimePicker.tsx, packages/components/src/components/time-picker/interfaces.ts, packages/components/stories/Validation.stories.tsx
https://perzoinc.atlassian.net/browse/APP-4937
**Changes**
Fix infinite loop on mobile
=> APP-4937 Fix infinite loop on mobile

spec/components/time-picker/TimePicker.spec.tsx, spec/components/validation/Validation.spec.tsx, src/components/time-picker/TimePicker.tsx, src/components/time-picker/utils/Time.tsx, src/components/time-picker/utils/timeUtils.tsx, src/components/validation/Validation.tsx, stories/Validation.stories.tsx
https://perzoinc.atlassian.net/browse/APP-4936
**Changes**
Apply fixes APP-4932 APP-4938 APP-4937
**Related PRs**
https://github.com/SymphonyPlatformSolutions/symphony-ui-toolkit/pull/455
https://github.com/SymphonyPlatformSolutions/symphony-ui-toolkit/pull/467
https://github.com/SymphonyPlatformSolutions/symphony-ui-toolkit/pull/462
https://github.com/SymphonyPlatformSolutions/symphony-ui-toolkit/pull/471
=> APP-4936 Apply fixes APP-4932 APP-4938 APP-4937

packages/styles/.circleci/config.yml
Disable temporary Visual Tests.
I created the ticket https://perzoinc.atlassian.net/browse/APP-5149 to not forget to fix it.
=> APP-5149 Disable Visual Tests (Creevy)

README.md
Describe the change, to make it easy for reviewers to understand the purpose and solution of the PR.
[JIRA_Ticket](https://perzoinc.atlassian.net/browse/APP-4638)
=> APP-4638 insert link to github pages in readme

packages/components/src/components/badge/Badge.tsx
Expose the ...rest of the div props in Badge component
[C2-17561](https://perzoinc.atlassian.net/browse/C2-17561)
=> Expose correct prop types in Badge

package.json, packages/components/package.json, packages/styles/package.json, yarn.lock
Describe the change, to make it easy for reviewers to understand the purpose and solution of the PR.
[JIRA_Ticket](https://perzoinc.atlassian.net/browse/JIRA_Ticket)
=> Fix for webpack with node v18 + update browserlist

packages/components/src/components/expandable-card/ExpandableCard.tsx, packages/components/src/components/icon/FontIcon.tsx, packages/styles/src/icons/_index.scss, packages/styles/src/icons/templates/tk-icons.scss.hbs, packages/styles/src/icons/templates/tk-icons.stories.js.hbs
- Revert #587 
- Revert #590 
- Add 'i' in the CSS icon selectos 
[C2-18455](https://perzoinc.atlassian.net/browse/C2-18455)
[C2-18455]: https://perzoinc.atlassian.net/browse/C2-18455?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> C2-18455 Revert #587 and #590 and add 'i' in the selector

packages/components/stories/Icons.stories.tsx
Fixing so they're visible on both dark/light theming.
=> Update icon styling in story

packages/components/src/components/modal/Modal.tsx
=> BYC-916: Apply `styled-scrollbars` style on `ModalBody` component

packages/components/src/components/dropdown-menu/DropdownMenu.tsx
Make dropdown menu item reachable with the keyboard
[CES-18071](https://perzoinc.atlassian.net/browse/CES-18071)
[CES-18071]: https://perzoinc.atlassian.net/browse/CES-18071?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CES-18071] Make dropdown menu item reachable with the keyboard

packages/components/package.json, packages/components/src/components/tooltip/Tooltip.tsx, yarn.lock
Tooltip doesn't disappear when hovering when a new DOM element overlays the previous one. Using an updated version of @floating-ui/react I can't reproduce it.
=> Fixing tooltip component

packages/components/src/components/banner/Banner.tsx, packages/styles/src/components/atoms/_banner.scss
Make banner accessible
- action button: remove `outline: none;` 
- close button : 
- use `button` balise
- remove `top: toRem(2);` to center the button in the outline when the button is focused
[CES-18232](https://perzoinc.atlassian.net/browse/CES-18232)
[CES-18232]: https://perzoinc.atlassian.net/browse/CES-18232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CES-18232] Make banner accessible

packages/components/spec/components/date-picker/DatePicker.spec.tsx, packages/components/src/components/date-picker/DatePicker.tsx
- Add more functions to handle open or close calendar
- Add condition to reset the datePicker's value to a valid one.
[C2-23836](https://perzoinc.atlassian.net/browse/C2-23836)
https://github.com/user-attachments/assets/d87fc76a-b494-45b6-b47b-f45c23b48d05
[C2-23836]: https://perzoinc.atlassian.net/browse/C2-23836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> C2-23836-uitoolkit: add more func for date picker

packages/components/spec/components/button/Button.spec.tsx, packages/components/src/components/button/Button.tsx
I need to focus a specific button after loading a modal, for that I need to pass a ref
https://perzoinc.atlassian.net/browse/RTC-15218
=> Allow to pass a ref to Buttons

packages/components/spec/components/nav/Nav.spec.tsx, packages/components/src/components/nav/Nav.tsx
Describe the change, to make it easy for reviewers to understand the purpose and solution of the PR.
[JIRA_Ticket](https://perzoinc.atlassian.net/browse/JIRA_Ticket)
=> Fix non-backward change

packages/components/src/components/dropdown/CustomRender.tsx
button to clear input in dropdown should have a role button
[JIRA_Ticket](https://perzoinc.atlassian.net/browse/CES-20279)
=> [CES-20279] button to clear input in dropdown should have a role button

packages/components/src/components/dropdown/CustomRender.tsx, packages/components/stories/Dropdown.stories.tsx
Handle required in dropdown so that the screen reader annonce it
[CES-20067](https://perzoinc.atlassian.net/browse/CES-20067)
[CES-20067]: https://perzoinc.atlassian.net/browse/CES-20067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CES-20067] Handle required in dropdown

packages/components/src/components/dropdown/CustomRender.tsx
Add an arial-label on the close icon in clear indicator in dropdown
[CES-20336](https://perzoinc.atlassian.net/browse/CES-20336)
[CES-20336]: https://perzoinc.atlassian.net/browse/CES-20336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CES-20336] Add an arial-label on the close icon in clear indicator in dropdown

packages/components/spec/components/date-picker/DatePicker.spec.tsx, packages/components/src/components/date-picker/DatePicker.tsx, packages/components/src/components/date-picker/sub-component/DayPicker.tsx, packages/components/src/components/date-picker/utils/dateConstants.ts
- add more func: focus to selected date when opening the DatePicker
[C2-24526](https://perzoinc.atlassian.net/browse/C2-24526)
https://github.com/user-attachments/assets/abbea188-ca2f-462c-b806-9f56fc68f00c
[C2-24526]: https://perzoinc.atlassian.net/browse/C2-24526?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> C2-24526-uitoolkit: update behavior to DatePicker

packages/components/README.md
```
yarn start
```
In another terminal, run:
```
cd ../styles
yarn run watch
```
=> README: Explain how to synchronize style changes with Storybook

packages/styles/src/uitoolkit-components/_select.scss
Fix a UI issue on dropdown component using an input with type="search".
[JIRA_Ticket](https://perzoinc.atlassian.net/browse/CES-20765)
https://github.com/user-attachments/assets/313e60aa-4ffa-4e58-9159-9be84ed4984b
=> [CES-20765] Fix dropdown style issue using input type as 'search'

packages/styles/src/uitoolkit-components/_select.scss
Apply [fix](https://github.com/SymphonyPlatformSolutions/symphony-ui-toolkit/pull/681) on v4.6.1
In order to publish a new v4.6.2 release
[CES-20765](https://perzoinc.atlassian.net/browse/CES-20765)
[CES-20765]: https://perzoinc.atlassian.net/browse/CES-20765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CES-20765] Fix dropdown style issue using input type as 'search' (#681)

packages/components/spec/components/date-picker/DatePicker.spec.tsx, packages/components/src/components/date-picker/DatePicker.tsx, packages/components/src/components/date-picker/sub-component/DayPicker.tsx, packages/components/src/components/date-picker/sub-component/Header.tsx, packages/components/src/components/date-picker/utils/dateConstants.ts, packages/components/src/components/tooltip/Tooltip.tsx, packages/styles/src/uitoolkit-components/_date-picker.scss
Temporary Revert C2-24526 to publish new release 4.6.2, because the publish.sh script (setVersion) doesn't support for now to publish a release from a branch 😢
=> Revert C2-24526 to publish new release 4.6.2

packages/components/spec/components/date-picker/DatePicker.spec.tsx, packages/components/src/components/date-picker/DatePicker.tsx, packages/components/src/components/date-picker/sub-component/DayPicker.tsx, packages/components/src/components/date-picker/sub-component/Header.tsx, packages/components/src/components/date-picker/utils/dateConstants.ts, packages/components/src/components/tooltip/Tooltip.tsx, packages/styles/src/uitoolkit-components/_date-picker.scss
Reverts SymphonyPlatformSolutions/symphony-ui-toolkit#683
=> Revert "Revert C2-24526 to publish new release 4.6.2" 🙃 

packages/components/src/components/dropdown/CustomRender.tsx
Add aria-describedBy and aria-invalid in Dropdown
[CES-20500](https://perzoinc.atlassian.net/browse/CES-20500)
[CES-20500]: https://perzoinc.atlassian.net/browse/CES-20500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CES-20500] Add aria-describedBy and aria-invalid in Dropdown

packages/components/src/components/date-picker/sub-component/Header.tsx, packages/components/src/components/dropdown/CustomRender.tsx
**CES-20500 | C2-24993: Fix console errors**
-------
- https://perzoinc.atlassian.net/browse/CES-20500 `aria-describedBy` --> `aria-describedby`
------
- https://perzoinc.atlassian.net/browse/C2-24993 date-picker `handleKeyDown` being `false`
=> CES-20500 | C2-24993: Fix console errors

packages/components/src/components/modal/Modal.tsx
Add aria-label to be read by voice over on modal opening
[CES-22162](https://perzoinc.atlassian.net/browse/CES-22162)
[CES-22162]: https://perzoinc.atlassian.net/browse/CES-22162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add aria-label to be read by voice over on modal opening

packages/components/src/components/dropdown-menu/DropdownMenu.tsx
This change was requested by one of our client to improve accessibility on dropdown menu. Voice over will now announce when we enter and leave a dropdown menu, it will also announce the position of the menu item in a list (eg: item 2/3)
[CES-21855](https://perzoinc.atlassian.net/browse/CES-21855)
[CES-21855]: https://perzoinc.atlassian.net/browse/CES-21855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Adding menu and menu-item role to dropdown menu to improve accessibility

packages/components/spec/components/dropdown-menu/DropdownMenu.spec.tsx, packages/components/src/components/dropdown-menu/DropdownMenu.tsx
Adding tabIndex props for DropdownMenuItem
https://perzoinc.atlassian.net/browse/C2-26678
=> Add tabIndex props for dropdown menu item

packages/components/.circleci/config.yml
=> Remove Code Climate reporter

packages/components/.circleci/config.yml, packages/components/src/components/dropdown/CustomRender.tsx, packages/components/src/components/dropdown/interfaces.ts, packages/components/stories/Dropdown.stories.tsx, packages/styles/.circleci/config.yml
Adding optional aria label property to dropdown input in case we want to customize text read by accessibility tools without displaying it.
[CES-23245](https://perzoinc.atlassian.net/browse/CES-23245)
[CES-23245]: https://perzoinc.atlassian.net/browse/CES-23245?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Adding optional aria label property to dropdown input
